compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  zero_optimization:
    stage: 2
    allgather_partitions: true
    allgather_bucket_size: 2e8
    overlap_comm: true
    reduce_scatter: true
    contiguous_gradients: true
  bf16:
    enabled: true
num_processes: 4